# Generated by Django 5.2.8 on 2026-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_membership_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=16),
        ),
    ]
