# Generated by Django 5.2.8 on 2026-04-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('olympiads', '0002_olympiad_season_choices'),
        ('teams', '0004_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiad'),
        ),
    ]
