# Generated by Django 5.2.8 on 2026-02-28 00:00

from django.db import migrations, models


def normalize_olympiad_season(apps, schema_editor):
    Olympiad = apps.get_model("olympiads", "Olympiad")

    Olympiad.objects.filter(season="2025-2026").update(season="2025/2026")
    Olympiad.objects.filter(season="").update(season="2025/2026")
    Olympiad.objects.filter(season__isnull=True).update(season="2025/2026")


class Migration(migrations.Migration):
    dependencies = [
        ("olympiads", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_olympiad_season, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="olympiad",
            name="season",
            field=models.CharField(
                choices=[
                    ("2025/2026", "2025/2026"),
                    ("2026/2027", "2026/2027"),
                    ("2027/2028", "2027/2028"),
                    ("2028/2029", "2028/2029"),
                    ("2029/2030", "2029/2030"),
                    ("2030/2031", "2030/2031"),
                    ("2031/2032", "2031/2032"),
                    ("2032/2033", "2032/2033"),
                    ("2033/2034", "2033/2034"),
                    ("2034/2035", "2034/2035"),
                    ("2035/2036", "2035/2036"),
                ],
                max_length=9,
            ),
        ),
    ]
