# Generated by Django 5.2.8 on 2026-04-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('olympiads', '0002_olympiad_season_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_olympiad', to='events.event'),
        ),
    ]
