# Generated by Django 5.2.8 on 2026-04-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_label', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_stages', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('registration_open', 'Registration open'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventEditionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_number', models.PositiveIntegerField()),
                ('stage_name', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.eventedition')),
            ],
        ),
        migrations.AddField(
            model_name='eventedition',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventeditionstage'),
        ),
        migrations.AddConstraint(
            model_name='eventeditionstage',
            constraint=models.UniqueConstraint(fields=('edition', 'stage_number'), name='uniq_event_edition_stage_number'),
        ),
        migrations.AddConstraint(
            model_name='eventeditionstage',
            constraint=models.CheckConstraint(condition=models.Q(('stage_number__gt', 0)), name='event_edition_stage_number_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='eventeditionstage',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='event_edition_stage_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.UniqueConstraint(fields=('event', 'edition_label'), name='uniq_event_edition_label'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.CheckConstraint(condition=models.Q(('total_stages__gt', 0)), name='event_edition_total_stages_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='event_edition_start_lte_end'),
        ),
    ]
