# Generated by Django 5.2.8 on 2026-04-20 07:42

from django.db import migrations, models


EVENT_TYPE_CODES = {
    "olympiad": "olympiad",
    "hackathon": "hackathon",
    "case-championship": "case_championship",
    "case_championship": "case_championship",
}

LEVEL_CODES = {
    "international": "international",
    "vsosh": "vsosh",
    "level-1": "level_1",
    "level_1": "level_1",
    "level-2": "level_2",
    "level_2": "level_2",
    "level-3": "level_3",
    "level_3": "level_3",
}

PARTICIPATION_MODES = {
    "INDIVIDUAL": "individual",
    "TEAM": "team",
    "BOTH": "hybrid",
}


def _normalize_code(value):
    if not value:
        return None
    return value.strip().lower().replace("-", "_").replace(" ", "_")


def _mapped_code(value, choices):
    if not value:
        return None
    normalized = _normalize_code(value)
    return choices.get(value.strip().lower()) or choices.get(normalized)


def backfill_event_flat_fields(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.select_related("event_type", "level").prefetch_related("profiles"):
        first_profile = event.profiles.order_by("id").first()
        # During the bridge phase, multi-profile events use the first profile by id
        # so the scalar profile_code backfill is deterministic.
        profile_code = None
        if first_profile:
            profile_code = first_profile.slug or _normalize_code(first_profile.name)

        event.name = event.title
        event.event_type_code = _mapped_code(event.event_type.slug, EVENT_TYPE_CODES)
        event.profile_code = profile_code
        event.level_code = _mapped_code(event.level.slug, LEVEL_CODES) if event.level_id else None
        event.participation_mode = PARTICIPATION_MODES.get(event.participation_type)
        event.save(
            update_fields=[
                "name",
                "event_type_code",
                "profile_code",
                "level_code",
                "participation_mode",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventedition_eventeditionstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type_code',
            field=models.CharField(blank=True, choices=[('olympiad', 'Olympiad'), ('hackathon', 'Hackathon'), ('case_championship', 'Case championship')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='level_code',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('vsosh', 'VSOSH'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_mode',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('team', 'Team'), ('hybrid', 'Hybrid')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='profile_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(backfill_event_flat_fields, noop_reverse),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='event_name_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type_code', 'profile_code'], name='event_type_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['level_code'], name='event_level_code_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['participation_mode'], name='event_participation_mode_idx'),
        ),
    ]
