# Generated by Django 5.2.8 on 2026-05-01 18:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_type_code_event_level_code_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eligible_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('grades_1_4', '1–4 классы'), ('grade_5', '5 класс'), ('grade_6', '6 класс'), ('grade_7', '7 класс'), ('grade_8', '8 класс'), ('grade_9', '9 класс'), ('grade_10', '10 класс'), ('grade_11', '11 класс'), ('student', 'Студент')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['eligible_groups'], name='event_eligible_groups_gin'),
        ),
    ]
