# Generated by Django 5.2.8 on 2026-05-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_eligible_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEditionAdmissionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.CharField(choices=[('bvi', 'BVI'), ('ege_100', 'EGE 100'), ('extra_points', 'Extra points'), ('discount', 'Discount'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('winner_benefit', models.CharField(blank=True, max_length=512)),
                ('prizewinner_benefit', models.CharField(blank=True, max_length=512)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('specialist', 'Specialist'), ('master', 'Master'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('code', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='eventedition',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventedition',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventeditionstage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventeditionstage',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='event_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='eventedition',
            index=models.Index(fields=['event', 'status'], name='event_edition_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventeditionstage',
            index=models.Index(fields=['edition', 'status'], name='stage_edition_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventedition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_start_date__isnull', True), ('registration_end_date__isnull', True), ('registration_start_date__lte', models.F('registration_end_date')), _connector='OR'), name='event_edition_reg_start_lte_end'),
        ),
        migrations.AddField(
            model_name='eventeditionadmissionbenefit',
            name='event_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_benefits', to='events.eventedition'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='university_name_idx'),
        ),
        migrations.AddField(
            model_name='eventeditionadmissionbenefit',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_benefits', to='events.university'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='events.university'),
        ),
        migrations.AddField(
            model_name='eventeditionadmissionbenefit',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='benefits', to='events.universityprogram'),
        ),
        migrations.AddIndex(
            model_name='universityprogram',
            index=models.Index(fields=['university', 'name'], name='univ_program_univ_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='universityprogram',
            constraint=models.UniqueConstraint(fields=('university', 'name', 'level'), name='uniq_univ_program'),
        ),
        migrations.AddIndex(
            model_name='eventeditionadmissionbenefit',
            index=models.Index(fields=['event_edition', 'university'], name='event_edition_benefit_univ_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventeditionadmissionbenefit',
            constraint=models.UniqueConstraint(fields=('event_edition', 'university', 'benefit_type'), name='uniq_event_edition_benefit'),
        ),
    ]
