# Generated by Django 5.2.8 on 2026-05-06 14:04

from datetime import date, timedelta
from django.db import migrations


def backfill_event_editions_and_stages(apps, schema_editor):
    """
    Backfill EventEdition and EventEditionStage from existing Event records.
    
    For each Event without editions, create a default EventEdition with:
    - edition_label based on the event's creation date (year or "legacy")
    - start_date and end_date from the event or default values
    - total_stages = 1 (default single stage per event)
    - A corresponding EventEditionStage
    
    This is idempotent: uses get_or_create with stable keys.
    No data is deleted.
    """
    Event = apps.get_model('events', 'Event')
    EventEdition = apps.get_model('events', 'EventEdition')
    EventEditionStage = apps.get_model('events', 'EventEditionStage')
    
    events_backfilled = 0
    stages_backfilled = 0
    
    for event in Event.objects.all():
        # Skip events that already have editions
        if event.editions.exists():
            continue
        
        # Determine edition_label from event creation date
        created_year = event.created_at.year if event.created_at else date.today().year
        edition_label = str(created_year)
        
        # Determine date range
        if event.registration_deadline:
            start_date = event.created_at.date() if event.created_at else date.today()
            end_date = min(event.registration_deadline, date.today() + timedelta(days=365))
        else:
            start_date = event.created_at.date() if event.created_at else date.today()
            end_date = start_date + timedelta(days=180)
        
        # Ensure start_date <= end_date
        if start_date > end_date:
            end_date = start_date + timedelta(days=180)
        
        # Create EventEdition if it doesn't exist
        edition, created = EventEdition.objects.get_or_create(
            event=event,
            edition_label=edition_label,
            defaults={
                'start_date': start_date,
                'end_date': end_date,
                'total_stages': 1,
                'status': 'draft',
                'registration_start_date': start_date,
                'registration_end_date': event.registration_deadline or end_date,
            }
        )
        
        if created:
            events_backfilled += 1
        
        # Create default EventEditionStage if edition has no stages
        if not edition.stages.exists():
            stage, stage_created = EventEditionStage.objects.get_or_create(
                edition=edition,
                stage_number=1,
                defaults={
                    'stage_name': 'Main Stage',
                    'start_date': start_date,
                    'end_date': end_date,
                    'status': 'planned',
                    'format': 'unknown',
                }
            )
            
            if stage_created:
                stages_backfilled += 1
            
            # Set current_stage on edition if not already set
            if not edition.current_stage_id:
                edition.current_stage = stage
                edition.save(update_fields=['current_stage'])
    
    print(f"✓ Backfill complete: {events_backfilled} editions + {stages_backfilled} stages created")


def reverse_backfill(apps, schema_editor):
    """
    Reverse: delete EventEdition and EventEditionStage records that were created
    by this migration. We identify them as editions with label matching the event's
    creation year and no explicit registration data.
    
    In practice, we should preserve data unless explicitly needed for cleanup.
    This is a conservative reverse that only deletes if truly safe.
    """
    Event = apps.get_model('events', 'Event')
    EventEdition = apps.get_model('events', 'EventEdition')
    
    # Conservative approach: only delete editions that look auto-generated
    # (single stage, default naming pattern)
    editions_to_delete = []
    
    for edition in EventEdition.objects.all():
        created_year = edition.event.created_at.year if edition.event.created_at else None
        if created_year and edition.edition_label == str(created_year):
            if edition.stages.count() == 1:
                stage = edition.stages.first()
                if stage.stage_name == 'Main Stage' and stage.stage_number == 1:
                    editions_to_delete.append(edition.id)
    
    if editions_to_delete:
        deleted_count, _ = EventEdition.objects.filter(id__in=editions_to_delete).delete()
        print(f"✓ Reverse: deleted {deleted_count} auto-generated editions")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventeditionadmissionbenefit_university_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_event_editions_and_stages, reverse_backfill),
    ]
