# Generated by Codex on 2026-05-18

from django.db import migrations


VSOSH_EVENTS = [
    {
        "name": "ВСОШ. Математика",
        "title": "ВСОШ. Математика",
        "profile_slug": "math",
        "profile_name": "Математика",
    },
    {
        "name": "ВСОШ. Труд",
        "title": "ВСОШ. Труд",
        "profile_slug": "technology",
        "profile_name": "Технология",
    },
    {
        "name": "ВСОШ. Экология",
        "title": "ВСОШ. Экология",
        "profile_slug": "ecology",
        "profile_name": "Экология",
    },
]


def seed_vsosh_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventLevel = apps.get_model("events", "EventLevel")
    EventProfile = apps.get_model("events", "EventProfile")
    EventType = apps.get_model("events", "EventType")

    olympiad_type, _ = EventType.objects.get_or_create(
        slug="olympiad",
        defaults={
            "name": "Olympiad",
            "is_active": True,
            "sort_order": 0,
        },
    )
    vsosh_level, _ = EventLevel.objects.get_or_create(
        slug="vsosh",
        defaults={
            "name": "ВСОШ",
            "is_active": True,
            "sort_order": 0,
        },
    )

    for index, item in enumerate(VSOSH_EVENTS, start=1):
        profile, _ = EventProfile.objects.get_or_create(
            slug=item["profile_slug"],
            defaults={
                "name": item["profile_name"],
                "is_active": True,
                "sort_order": index,
            },
        )

        event, _ = Event.objects.update_or_create(
            title=item["title"],
            defaults={
                "name": item["name"],
                "short_description": "",
                "description": "",
                "official_url": "",
                "organizer": "ВСОШ",
                "is_active": True,
                "event_type_code": "olympiad",
                "profile_code": item["profile_slug"],
                "level_code": "vsosh",
                "participation_mode": "individual",
                "event_type": olympiad_type,
                "level": vsosh_level,
                "participation_type": "INDIVIDUAL",
                "preferences": "",
            },
        )
        event.profiles.set([profile])


def unseed_vsosh_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title__in=[item["title"] for item in VSOSH_EVENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_backfill_event_editions_and_stages"),
    ]

    operations = [
        migrations.RunPython(seed_vsosh_events, unseed_vsosh_events),
    ]
