# Generated by Codex on 2026-05-18

from django.db import migrations


VSOSH_INFORMATICS_EVENTS = [
    {
        "name": "ВСОШ. Искусственный Интеллект",
        "title": "ВСОШ. Искусственный Интеллект",
        "profile_slug": "artificial_intelligence",
        "profile_name": "Информатика. ИИ",
    },
    {
        "name": "ВСОШ. Информатика",
        "title": "ВСОШ. Информатика",
        "profile_slug": "olymp_prog",
        "profile_name": "Информатика. Ол. Прога",
    },
    {
        "name": "ВСОШ. Робототехника",
        "title": "ВСОШ. Робототехника",
        "profile_slug": "robotics",
        "profile_name": "Информатика. Робототехника",
    },
    {
        "name": "ВСОШ. ИнфоБез",
        "title": "ВСОШ. ИнфоБез",
        "profile_slug": "infosec",
        "profile_name": "Информатика. ИнфоБез",
    },
]


def seed_vsosh_informatics_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventLevel = apps.get_model("events", "EventLevel")
    EventProfile = apps.get_model("events", "EventProfile")
    EventType = apps.get_model("events", "EventType")

    olympiad_type, _ = EventType.objects.get_or_create(
        slug="olympiad",
        defaults={
            "name": "Olympiad",
            "is_active": True,
            "sort_order": 0,
        },
    )
    vsosh_level, _ = EventLevel.objects.get_or_create(
        slug="vsosh",
        defaults={
            "name": "ВСОШ",
            "is_active": True,
            "sort_order": 0,
        },
    )

    for index, item in enumerate(VSOSH_INFORMATICS_EVENTS, start=1):
        profile, created = EventProfile.objects.get_or_create(
            slug=item["profile_slug"],
            defaults={
                "name": item["profile_name"],
                "is_active": True,
                "sort_order": index,
            },
        )
        if not created:
            profile.name = item["profile_name"]
            profile.is_active = True
            if not profile.sort_order:
                profile.sort_order = index
            profile.save(update_fields=["name", "is_active", "sort_order"])

        event, _ = Event.objects.update_or_create(
            title=item["title"],
            defaults={
                "name": item["name"],
                "short_description": "",
                "description": "",
                "official_url": "",
                "organizer": "ВСОШ",
                "is_active": True,
                "event_type_code": "olympiad",
                "profile_code": item["profile_slug"],
                "level_code": "vsosh",
                "participation_mode": "individual",
                "event_type": olympiad_type,
                "level": vsosh_level,
                "participation_type": "INDIVIDUAL",
                "preferences": "",
            },
        )
        event.profiles.set([profile])


def unseed_vsosh_informatics_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title__in=[item["title"] for item in VSOSH_INFORMATICS_EVENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_seed_vsosh_events"),
    ]

    operations = [
        migrations.RunPython(seed_vsosh_informatics_events, unseed_vsosh_informatics_events),
    ]
