# Generated by Codex on 2026-05-18

from django.db import migrations


OLYMPIAD_EVENTS = [
    {
        "name": "Высшая Проба. Математика",
        "title": "Высшая Проба. Математика",
        "profile_slug": "math",
        "profile_name": "Математика",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Финансовая грамотность",
        "title": "Высшая Проба. Финансовая грамотность",
        "profile_slug": "financial_literacy",
        "profile_name": "Финансовая грамотность",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Дизайн",
        "title": "Высшая Проба. Дизайн",
        "profile_slug": "design",
        "profile_name": "Дизайн",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Журналистика",
        "title": "Высшая Проба. Журналистика",
        "profile_slug": "journalism",
        "profile_name": "Журналистика",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Инженерные Науки",
        "title": "Высшая Проба. Инженерные Науки",
        "profile_slug": "engineering_sciences",
        "profile_name": "Инженерные Науки",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Основы Бизнеса",
        "title": "Высшая Проба. Основы Бизнеса",
        "profile_slug": "business_fundamentals",
        "profile_name": "Основы Бизнеса",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "Высшая Проба. Международные Отношения",
        "title": "Высшая Проба. Международные Отношения",
        "profile_slug": "international_relations",
        "profile_name": "Международные Отношения",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
        "participation_mode": "individual",
        "participation_type": "INDIVIDUAL",
    },
    {
        "name": "DANO",
        "title": "DANO",
        "profile_slug": "data_analysis",
        "profile_name": "Анализ Данных",
        "level_slug": "level-3",
        "level_name": "3 уровень",
        "level_code": "level_3",
        "participation_mode": "hybrid",
        "participation_type": "BOTH",
    },
]


def seed_highest_probe_and_dano_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventLevel = apps.get_model("events", "EventLevel")
    EventProfile = apps.get_model("events", "EventProfile")
    EventType = apps.get_model("events", "EventType")

    olympiad_type, _ = EventType.objects.get_or_create(
        slug="olympiad",
        defaults={
            "name": "Olympiad",
            "is_active": True,
            "sort_order": 0,
        },
    )

    for index, item in enumerate(OLYMPIAD_EVENTS, start=1):
        profile, created = EventProfile.objects.get_or_create(
            slug=item["profile_slug"],
            defaults={
                "name": item["profile_name"],
                "is_active": True,
                "sort_order": index,
            },
        )
        if not created:
            profile.name = item["profile_name"]
            profile.is_active = True
            if not profile.sort_order:
                profile.sort_order = index
            profile.save(update_fields=["name", "is_active", "sort_order"])

        level, _ = EventLevel.objects.get_or_create(
            slug=item["level_slug"],
            defaults={
                "name": item["level_name"],
                "is_active": True,
                "sort_order": index,
            },
        )

        organizer = "DANO" if item["name"] == "DANO" else "Высшая Проба"
        event, _ = Event.objects.update_or_create(
            title=item["title"],
            defaults={
                "name": item["name"],
                "short_description": "",
                "description": "",
                "official_url": "",
                "organizer": organizer,
                "is_active": True,
                "event_type_code": "olympiad",
                "profile_code": item["profile_slug"],
                "level_code": item["level_code"],
                "participation_mode": item["participation_mode"],
                "event_type": olympiad_type,
                "level": level,
                "participation_type": item["participation_type"],
                "preferences": "",
            },
        )
        event.profiles.set([profile])


def unseed_highest_probe_and_dano_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title__in=[item["title"] for item in OLYMPIAD_EVENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_seed_vsosh_humanities_events"),
    ]

    operations = [
        migrations.RunPython(seed_highest_probe_and_dano_events, unseed_highest_probe_and_dano_events),
    ]
