# Generated by Codex on 2026-05-18

from django.db import migrations


HIGH_PROBE_NATURAL_SCIENCE_EVENTS = [
    {
        "name": "Высшая Проба. Физика",
        "title": "Высшая Проба. Физика",
        "profile_slug": "physics",
        "profile_name": "Естественные науки. Физика",
    },
    {
        "name": "Высшая Проба. География",
        "title": "Высшая Проба. География",
        "profile_slug": "geography",
        "profile_name": "География",
    },
    {
        "name": "Высшая Проба. Биология",
        "title": "Высшая Проба. Биология",
        "profile_slug": "biology",
        "profile_name": "Биология",
    },
    {
        "name": "Высшая Проба. Химия",
        "title": "Высшая Проба. Химия",
        "profile_slug": "chemistry",
        "profile_name": "Химия",
    },
]


def seed_high_probe_natural_science_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventLevel = apps.get_model("events", "EventLevel")
    EventProfile = apps.get_model("events", "EventProfile")
    EventType = apps.get_model("events", "EventType")

    olympiad_type, _ = EventType.objects.get_or_create(
        slug="olympiad",
        defaults={
            "name": "Olympiad",
            "is_active": True,
            "sort_order": 0,
        },
    )

    for index, item in enumerate(HIGH_PROBE_NATURAL_SCIENCE_EVENTS, start=1):
        profile, created = EventProfile.objects.get_or_create(
            slug=item["profile_slug"],
            defaults={
                "name": item["profile_name"],
                "is_active": True,
                "sort_order": index,
            },
        )
        if not created:
            profile.name = item["profile_name"]
            profile.is_active = True
            if not profile.sort_order:
                profile.sort_order = index
            profile.save(update_fields=["name", "is_active", "sort_order"])

        level, _ = EventLevel.objects.get_or_create(
            slug="level-2",
            defaults={
                "name": "2 уровень",
                "is_active": True,
                "sort_order": index,
            },
        )

        event, _ = Event.objects.update_or_create(
            title=item["title"],
            defaults={
                "name": item["name"],
                "short_description": "",
                "description": "",
                "official_url": "",
                "organizer": "Высшая Проба",
                "is_active": True,
                "event_type_code": "olympiad",
                "profile_code": item["profile_slug"],
                "level_code": "level_2",
                "participation_mode": "individual",
                "event_type": olympiad_type,
                "level": level,
                "participation_type": "INDIVIDUAL",
                "preferences": "",
            },
        )
        event.profiles.set([profile])


def unseed_high_probe_natural_science_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title__in=[item["title"] for item in HIGH_PROBE_NATURAL_SCIENCE_EVENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_seed_highest_probe_and_dano_events"),
    ]

    operations = [
        migrations.RunPython(seed_high_probe_natural_science_events, unseed_high_probe_natural_science_events),
    ]
