# Generated by Codex on 2026-05-20

from django.db import migrations


HIGH_PROBE_EVENTS = [
    {
        "name": "Высшая Проба. Английский Язык",
        "title": "Высшая Проба. Английский Язык",
        "profile_slug": "english",
        "profile_name": "Английский Язык",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Испанский Язык",
        "title": "Высшая Проба. Испанский Язык",
        "profile_slug": "spanish",
        "profile_name": "Испанский Язык",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Немецкий Язык",
        "title": "Высшая Проба. Немецкий Язык",
        "profile_slug": "german",
        "profile_name": "Немецкий Язык",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Французский Язык",
        "title": "Высшая Проба. Французский Язык",
        "profile_slug": "french",
        "profile_name": "Французский Язык",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. История",
        "title": "Высшая Проба. История",
        "profile_slug": "history",
        "profile_name": "История и Культура. История",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. История Искусств",
        "title": "Высшая Проба. История Искусств",
        "profile_slug": "art_history",
        "profile_name": "История и Культура. История Искусств",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
    {
        "name": "Культурология",
        "title": "Культурология",
        "profile_slug": "cultural_studies",
        "profile_name": "Культурология",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Востоковедение",
        "title": "Высшая Проба. Востоковедение",
        "profile_slug": "oriental_studies",
        "profile_name": "Востоковедение",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
    {
        "name": "Высшая Проба. Русский Язык",
        "title": "Высшая Проба. Русский Язык",
        "profile_slug": "russian_language",
        "profile_name": "Гуманитарные науки. Русский Язык",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
    {
        "name": "Высшая Проба. Филология",
        "title": "Высшая Проба. Филология",
        "profile_slug": "philology",
        "profile_name": "Гуманитарные науки. Филология",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Восточные Языки",
        "title": "Высшая Проба. Восточные Языки",
        "profile_slug": "eastern_languages",
        "profile_name": "Гуманитарные науки. Восточные Языки",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Обществознание",
        "title": "Высшая Проба. Обществознание",
        "profile_slug": "social_studies",
        "profile_name": "Обществознание",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Экономика",
        "title": "Высшая Проба. Экономика",
        "profile_slug": "economics",
        "profile_name": "Экономика",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Философия",
        "title": "Высшая Проба. Философия",
        "profile_slug": "philosophy",
        "profile_name": "Философия",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
    {
        "name": "Психология",
        "title": "Психология",
        "profile_slug": "psychology",
        "profile_name": "Психология",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
    {
        "name": "Право",
        "title": "Право",
        "profile_slug": "law",
        "profile_name": "Право",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Информатика",
        "title": "Высшая Проба. Информатика",
        "profile_slug": "olymp_prog",
        "profile_name": "Ол. Прога",
        "level_slug": "level-1",
        "level_name": "1 уровень",
        "level_code": "level_1",
    },
    {
        "name": "Высшая Проба. Пром. Прога",
        "title": "Высшая Проба. Пром. Прога",
        "profile_slug": "prom_prog",
        "profile_name": "Пром. Прога",
        "level_slug": "level-2",
        "level_name": "2 уровень",
        "level_code": "level_2",
    },
]


def seed_high_probe_languages_humanities_and_cs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    EventLevel = apps.get_model("events", "EventLevel")
    EventProfile = apps.get_model("events", "EventProfile")
    EventType = apps.get_model("events", "EventType")

    olympiad_type, _ = EventType.objects.get_or_create(
        slug="olympiad",
        defaults={
            "name": "Olympiad",
            "is_active": True,
            "sort_order": 0,
        },
    )

    for index, item in enumerate(HIGH_PROBE_EVENTS, start=1):
        profile, created = EventProfile.objects.get_or_create(
            slug=item["profile_slug"],
            defaults={
                "name": item["profile_name"],
                "is_active": True,
                "sort_order": index,
            },
        )
        if not created:
            profile.name = item["profile_name"]
            profile.is_active = True
            if not profile.sort_order:
                profile.sort_order = index
            profile.save(update_fields=["name", "is_active", "sort_order"])

        level, _ = EventLevel.objects.get_or_create(
            slug=item["level_slug"],
            defaults={
                "name": item["level_name"],
                "is_active": True,
                "sort_order": index,
            },
        )

        event, _ = Event.objects.update_or_create(
            title=item["title"],
            defaults={
                "name": item["name"],
                "short_description": "",
                "description": "",
                "official_url": "",
                "organizer": "Высшая Проба",
                "is_active": True,
                "event_type_code": "olympiad",
                "profile_code": item["profile_slug"],
                "level_code": item["level_code"],
                "participation_mode": "individual",
                "event_type": olympiad_type,
                "level": level,
                "participation_type": "INDIVIDUAL",
                "preferences": "",
            },
        )
        event.profiles.set([profile])


def unseed_high_probe_languages_humanities_and_cs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(title__in=[item["title"] for item in HIGH_PROBE_EVENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_seed_high_probe_natural_sciences"),
    ]

    operations = [
        migrations.RunPython(
            seed_high_probe_languages_humanities_and_cs,
            unseed_high_probe_languages_humanities_and_cs,
        ),
    ]
