/**
 * Database Seed Script
 * 
 * This script populates the database with 2025 team competitions
 * for the Browse Olympiads feature.
 * 
 * Competitions included:
 * 1. Northern Eurasia Finals 2025 (ICPC Regional)
 * 2. AIDAO — AI and Data Analysis Olympiad
 * 3. Russian Olympiad in Artificial Intelligence 2025
 * 4. ВКОШП — National School Team Programming Contest
 * 
 * Run with: npx prisma db seed
 * Or manually: npx ts-node prisma/seed.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * 2025 Team Competitions Data
 * 
 * Each entry contains:
 * - id: Unique identifier (auto-generated by Prisma)
 * - name: Full official name
 * - shortName: Abbreviated code (unique)
 * - description: Detailed description with eligibility, format, prizes
 * - year: Competition year
 * - level: "international" | "national" | "regional"
 * - subject: Category tag for filtering
 * - website: Official URL
 * - startDate/endDate: Competition dates
 */
const olympiads2025 = [
  {
    // Northern Eurasia Finals 2025 - ICPC Regional Championship
    // Source: ICPC official site and NEF regional info
    name: "Northern Eurasia Finals 2025",
    shortName: "NEF-2025",
    description: `Северо-восточный европейский региональный чемпионат ICPC (Northern Eurasia Finals) — престижное командное соревнование по программированию.

🏆 Формат: Команды из 3 человек решают алгоритмические задачи за 5 часов.
📍 Место проведения: Финал проходит очно в одном из городов региона.
🎯 Отбор: Через четвертьфиналы ICPC в университетах региона.

Победители получают право участвовать в ICPC World Finals — мировом финале чемпионата по программированию.

Участники: Студенты университетов Северной Евразии (Россия, Беларусь, Казахстан, и др.)`,
    year: 2025,
    level: "regional",
    subject: "Спортивное программирование",
    website: "https://neerc.ifmo.ru/",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-02"),
  },
  {
    // AIDAO - Artificial Intelligence and Data Analysis Olympiad
    // Source: Official AIDAO website
    name: "AIDAO — Олимпиада по искусственному интеллекту и анализу данных",
    shortName: "AIDAO-2025",
    description: `AIDAO (Artificial Intelligence and Data Analysis Olympiad) — командная олимпиада по машинному обучению и анализу данных для студентов и школьников.

🏆 Формат: Команды из 2-4 человек решают задачи по ML и Data Science.
📍 Этапы: Онлайн отборочный тур → Очный финал.
🎁 Призы: Денежные призы, гранты на обучение, стажировки в ведущих IT-компаниях.

🎯 Участники: Студенты и школьники старших классов.
📚 Тематика: Машинное обучение, нейронные сети, анализ данных, компьютерное зрение, NLP.

Организаторы: Ведущие технические университеты России при поддержке IT-индустрии.`,
    year: 2025,
    level: "national",
    subject: "Машинное обучение",
    website: "https://ai-dao.ru/",
    startDate: new Date("2025-02-15"),
    endDate: new Date("2025-04-20"),
  },
  {
    // Russian Olympiad in Artificial Intelligence 2025
    // Source: Official olympiad resources
    name: "Всероссийская олимпиада по искусственному интеллекту 2025",
    shortName: "AI-OLYMP-2025",
    description: `Всероссийская олимпиада школьников по искусственному интеллекту — официальная олимпиада для учащихся 8-11 классов.

🏆 Формат: Индивидуальное и командное участие на разных этапах.
📍 Этапы: Школьный → Муниципальный → Региональный → Заключительный.
🎁 Льготы: Победители и призёры получают льготы при поступлении в вузы.

📚 Задания включают:
• Основы машинного обучения
• Работа с данными и их анализ
• Программирование алгоритмов ИИ
• Решение прикладных задач

🎯 Возраст: Школьники 8-11 классов (14-18 лет).`,
    year: 2025,
    level: "national",
    subject: "Машинное обучение",
    website: "https://ai.rosolymp.ru/",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-04-15"),
  },
  {
    // ВКОШП - National School Team Programming Contest
    // Source: Official ВКОШП/ВКОШ information
    name: "Всероссийская командная олимпиада школьников по программированию (ВКОШП)",
    shortName: "ВКОШП-2025",
    description: `ВКОШП — главное командное соревнование по программированию среди школьников России, являющееся частью отборочной системы на Northern Eurasia Finals для школьных команд.

🏆 Формат: Команды из 3 школьников решают алгоритмические задачи в стиле ICPC.
📍 Этапы: Региональные отборы → Всероссийский финал.
🎁 Призы: Дипломы, путёвка на NEF для лучших команд, призы от спонсоров.

📚 Тематика задач:
• Алгоритмы и структуры данных
• Динамическое программирование
• Графы и деревья
• Геометрия и математика

🎯 Участники: Школьники 7-11 классов, команды по 3 человека.
🔗 Связь с NEF: Лучшие команды получают приглашение на Northern Eurasia Finals.`,
    year: 2025,
    level: "national",
    subject: "Спортивное программирование",
    website: "https://neerc.ifmo.ru/school/",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-12-15"),
  },
  {
    // Additional: Data Analysis focused competition
    name: "Цифровой прорыв — Хакатон по анализу данных 2025",
    shortName: "DIGITAL-2025",
    description: `«Цифровой прорыв» — всероссийский хакатон для команд, работающих с данными и создающих цифровые решения.

🏆 Формат: Команды из 3-5 человек решают реальные кейсы от компаний-партнёров за 48 часов.
📍 Этапы: Онлайн-отбор → Региональные финалы → Всероссийский финал.
🎁 Призы: Призовой фонд более 10 млн рублей, стажировки, гранты.

📚 Треки:
• Анализ больших данных (Big Data)
• Машинное обучение и ИИ
• Визуализация данных
• Бизнес-аналитика

🎯 Участники: Студенты, молодые специалисты до 35 лет.
🔧 Технологии: Python, SQL, ML-фреймворки, BI-инструменты.`,
    year: 2025,
    level: "national",
    subject: "Анализ данных",
    website: "https://hacks-ai.ru/",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-11-30"),
  },
];

/**
 * Main seed function
 * Upserts olympiad records - updates if exists, creates if new
 */
async function main() {
  console.log("🌱 Starting database seed...\n");

  for (const olympiad of olympiads2025) {
    // Use upsert to avoid duplicates on re-run
    const result = await prisma.olympiad.upsert({
      where: { shortName: olympiad.shortName },
      update: {
        name: olympiad.name,
        description: olympiad.description,
        year: olympiad.year,
        level: olympiad.level,
        subject: olympiad.subject,
        website: olympiad.website,
        startDate: olympiad.startDate,
        endDate: olympiad.endDate,
      },
      create: olympiad,
    });

    console.log(`✅ Upserted: ${result.shortName} - ${result.name}`);
  }

  console.log("\n🎉 Seed completed successfully!");
  console.log(`   Total olympiads: ${olympiads2025.length}`);
}

// Execute seed
main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
