# Generated by Django 5.2 on 2026-02-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_existing_teams(apps, schema_editor):
    CompetitionTeam = apps.get_model("competitions", "CompetitionTeam")
    CompetitionTeam.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionteam",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_competition_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(clear_existing_teams, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="competitionteam",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_competition_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
