# Generated by Django 5.2 on 2026-02-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_competitionteam_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetitionTeamMembership",
            new_name="CompetitionTeamRequest",
        ),
        migrations.AlterField(
            model_name="competitionteamrequest",
            name="competition_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="competitions.competitionteam",
            ),
        ),
        migrations.AlterField(
            model_name="competitionteamrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_team_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
